version: "3.7"

services:
  # data base image
  db:
    image: mysql:5.7.34
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: iclinic
      MYSQL_ROOT_PASSWORD: iclinic
    volumes:
      - .dbdataa:/var/lib/mysql
    ports:
      - "3306:3306"

  # iclinic prescription api
  iclinic:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    volumes:
      - .:/app
    depends_on:
      - db

