version: "3.7"

services:
  # data base image
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: iclinic
      POSTGRES_USER: iclinic
      POSTGRES_PASSWORD: iclinic

  # iclinic prescription api
  iclinic:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

